name: Tests
on: push
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Print info about environment
        run: go version
      - name: Install dependencies
        run: |
          ./run install
      - name: Lint
        run: |
          [[ $(./run format | wc -l | awk '{print $1}') = 0 ]] && $(exit 0) || $(exit 1)
      - name: Run tests
        run: |
          ./run test
